# BE CAREFUL MODIFYING THIS FILE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispute
spec:
  selector:
    matchLabels:
      app: dispute
  replicas: 3
  template:
    metadata:
      labels:
        app: dispute
    spec:
      containers:
      - name: dispute
        image: gcr.io/gems-org/dispute:VERSION
        command: ["./dispute"]
        args: ["--env=production"]
        env:
        - name: DISPUTE_DB_HOST
          value: "cloudsql-proxy"
        - name: DISPUTE_DB_PORT
          value: "3306"
        - name: DISPUTE_DB_NAME
          value: "dispute"
        - name: DISPUTE_DB_USER
          valueFrom:
            configMapKeyRef:
              name: dispute-data
              key: DISPUTE_DB_USER
        - name: DISPUTE_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: dispute-data
              key: DISPUTE_DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: dispute-data
              key: JWT_SECRET
        resources: {}
      
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dispute-migration
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: dispute-migration
    spec:
      containers:
      - name: dispute-migration
        image: gcr.io/gems-org/dispute-migration:VERSION
        args: ["composeup"]
        env:
        - name: DISPUTE_DB_HOST
          value: "cloudsql-proxy"
        - name: DISPUTE_DB_PORT
          value: "3306"
        - name: DISPUTE_DB_NAME
          value: "dispute"
        - name: DISPUTE_DB_USER
          valueFrom:
            configMapKeyRef:
              name: dispute-data
              key: DISPUTE_DB_USER
        - name: DISPUTE_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: dispute-data
              key: DISPUTE_DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
---

apiVersion: v1
kind: Service
metadata:
  name: dispute
spec:
  selector:
    app: dispute
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

